// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lytvhbetmrxyhkisszpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5dHZoYmV0bXJ4eWhraXNzenBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDMwNTEsImV4cCI6MjA3MDgxOTA1MX0.7cUAezTVfj3IA3xQT3rlsZDvBmAxi6W_-kPRroTENxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});